# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend PR checks

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: "frontend: npm i"
      run: npm i
      working-directory: frontend
    - name: "frontend: npm run lint"
      run: npm run lint
      working-directory: frontend
    - name: "frontend: npm run build"
      run: npm run build
      working-directory: frontend
