# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend PR checks

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: "backend: npm i"
      run: npm i
      working-directory: backend
    - name: "backend: npm run lint"
      run: npm run lint
      working-directory: backend
    - name: "backend: npm run prettier-check"
      run: npm run prettier-check
      working-directory: backend
